name: Release for Ubuntu 18.04
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Prepare
        run: |
          sudo ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
          sudo apt-get update && sudo apt-get install -y alsa-base autoconf bison build-essential dssi-dev file libasio-dev libasound2-dev libgig-dev libjack-dev libsndfile-dev libsqlite3-dev lv2-dev wget

      - name: Checkout
        run: |
          wget -nv https://download.linuxsampler.org/packages/linuxsampler-2.1.1.tar.bz2
          tar -xvf linuxsampler-2.1.1.tar.bz2
          mkdir linuxsampler-2.1.1/linuxsampler-2.1.1

      - name: Configure
        run: |
          cd linuxsampler-2.1.1
          PREFIX=$(pwd)/linuxsampler-2.1.1
          ./configure --prefix $PREFIX

      - name: Build
        run: |
          make -j8
          make install

      - name: Pack
        run: |
          tar -czvf linuxsampler-2.1.1.tar.gz linuxsampler-2.1.1
  